config/routes.rb
Humanmachine::Application.routes.draw do
  Rails.application.routes.default_url_options[:protocol]="https"
  get "welcome/index"
  get "welcome/contact"
  get "welcome/tos"
  get "uploads/create"
  get "uploads/authenticate_asset" => "uploads#authenticate_asset"

  resources :courses do
    resources :assignments, shallow: true
    collection do
      get 'help'
      get 'about'
    end
    member do
      post 'regenerate_consumer_secret'
      post 'enroll_lti'
      post 'make_instructor'
      get 'instructor_list'
    end
  end

  resources :assignments do
    resources :answers, shallow: true
    member do
      get 'stats'
      get 'grades'
      get 'export_grades'
      post 'update_grade/:grade_id' => "assignments#update_grade", as: :update_grade
      post 'resolve' => 'assignments#resolve_action_item', as: :resolve_action_item
      get "show_all_answers"
      get 'review_first'
      post 'create_typed_review' => 'reviews#create_with_type'
      get 'waitlist'
      get 'flipbook'
      post 'regrade'
    end
  end

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", :registrations => "registrations" }

  devise_scope :user do
    get 'users/start' => 'registrations#start_openid', :as => :start_openid_registration
    post 'users/complete' => 'registrations#complete_openid', :as => :complete_openid_registration
    get 'users/impersonate' => 'registrations#impersonate', :as=>:impersonate_user
    post 'users/upload' => 'registrations#upload', as: :upload_users
    get 'users/import' => 'registrations#import'
    get 'sessions/toggle' => 'application#toggle_view_mode', as: :toggle_view_mode
  end

  resources :answers do
    collection do
      get 'import'
      post 'upload'
    end
    member do
      post 'upload_attachment'
      post 'direct_upload_attachment'
      delete 'delete_attachment'
      get 'star' => 'answers#star'
      get 'submit_for_feedback' => 'answers#feedback_preferences'
      post 'submit_for_feedback'
      post 'unsubmit_for_feedback'
      post 'submit_for_grades'
      post 'unsubmit_for_grades'
      get 'reflect'
      post 'clone'
      post 'upgrade'
    end
    resources :reviews, shallow: true
  end

  get 'reviews/:id/rate' => "reviews#rate", as: :rate_review
  post 'reviews/:id/rate' => "reviews#create_rating", as: :create_rate_review
  post 'reviews/:id/blank' => "reviews#report_blank", as: :report_blank_answer
  post 'reviews/:answer_id/review_answer' => "reviews#review_answer", as: :review_answer

  resources :questions do
  end

  resources :rubric_items do
    resources :answer_attributes, shallow: true
  end

  authenticated do
    root :to => 'courses#index', as: :authenticated
  end
  root :to => 'welcome#index'

  post "connect/assignments/:id" => "lti#enroll_in_assignment", as: :lti_enrollment
  get "connect/complete/:id" => "lti#complete_enrollment", as: :complete_lti_enrollment
  get "connect/test" => "lti#test"
  get "connect/guide/:id" => "lti#guide"

end

app/controllers/assignments_controller.rb
class AssignmentsController < ApplicationController
  # include Humanize
  assignment_actions = [:show, :show_all_answers, :edit, :update, :destroy, :stats, :grades,
      :export_grades, :resolve_action_item, :review_first, :flipbook, :regrade, :update_grade]

  before_action :set_assignment, only: assignment_actions
  # add_breadcrumb :set_breadcrumb_link, only: assignment_actions
  before_action :set_course, only: [:index, :new, :create]
  before_filter :authenticate_user!, except: :show
  before_filter :authenticate_user_is_instructor_for_this_assignment!, only: [:flipbook, :stats, :update_grade, :export_grades, :edit, :regrade]
  # GET /assignments
  # GET /assignments.json
  def index
    redirect_to course_path @course #Easiest to put things in one place
  end

  # GET /assignments/1
  # GET /assignments/1.json
  def show
    if user_signed_in?
      @trigger = TriggerAction.pending_action("review_required", current_user, @assignment)
      @my_answers = Answer.where(user: current_user, assignment: @assignment, active: true)
      @my_reviews = Review.where(answer_id: @my_answers, active: true, assignment_id: @assignment.id)

      if current_user.get_and_store_experimental_condition!(@assignment.course) == "batched_email"
        @my_reviews = Review.where(answer_id: @my_answers, active: true, assignment_id: @assignment.id).where('created_at < ?', 1.day.ago)
      end
      @reviews_by_me = Review.where(active: true, assignment_id: @assignment.id).where("user_id = ? or copilot_email = ?", current_user.id,current_user.email)
      @out_of_box_answers_with_count = Review.where(assignment_id: @assignment.id, out_of_box_answer: true).group(:answer_id).count

      unless @out_of_box_answers_with_count.blank?
        @out_of_box_answers = @out_of_box_answers_with_count.reject {|k,v| v < 2 }
      end
      if @out_of_box_answers.blank?
        @out_of_box_answers = {}
      end
    end
    @all_answers = @assignment.answers.reviewable.limit(10)
    @starred_answers = @assignment.answers.reviewable.where(starred: true)
    render layout: "one_column"
  end

  def show_all_answers
    @all_answers = @assignment.answers.reviewable
    respond_to do |format|
      format.js
    end
  end


  def flipbook
    @answers = @assignment.answers.where(submitted: true).paginate(:page => params[:page], :per_page=>1)
    render layout: "one_column"
  end
  # GET /assignments/new
  def new
    #Course id is set in callback
    @assignment = Assignment.new(:course=>@course)
    render layout: "one_column"
  end

  # GET /assignments/1/edit
  def edit
    #noop
    render layout: "one_column"
  end

  #POST /regrade
  def regrade
    @assignment.regrade!
    redirect_to stats_assignment_path(@assignment), notice: "Regrade started; grades may take upto ten minutes to show on this page."
  end

  # POST /assignments
  # POST /assignments.json
  def create
    # raise params.inspect
    @assignment = Assignment.new(assignment_params)
    @assignment.course = Course.find(params[:course_id])
    @assignment.user=current_user
    respond_to do |format|
      if @assignment.save
        format.html { redirect_to @assignment, notice: 'Assignment was successfully created.' }
        format.json { render action: 'show', status: :created, location: @assignment }
      else
        format.html { render action: 'new' }
        format.json { render json: @assignment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /assignments/1
  # PATCH/PUT /assignments/1.json
  def update
    # raise assignment_params.inspect
    respond_to do |format|
      if @assignment.update(assignment_params)
        format.html { redirect_to @assignment, notice: 'Assignment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @assignment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /assignments/1
  # DELETE /assignments/1.json
  def destroy
    @course = @assignment.course
    @assignment.destroy
    respond_to do |format|
      format.html { redirect_to course_assignments_url(@course) }
      format.json { head :no_content }
    end
  end

  def stats
    # Data for more stats
    # @students = @assignment.course.students
    # @milestones = @assignment.milestones

    # @action_items = ActionItem.where(assignment: @assignment)

    @reviews_last_day_lagging = Review.where(assignment: @assignment).where("completed_at > ?", Time.now-1.day).count
    @submissions_last_day_lagging = @assignment.answers.where("submitted_at > ?", Time.now-1.day).count
    @submissions_last_day_havent_seen_reviews = @assignment.answers.where("submitted_at > ?", Time.now-1.day).where(reviews_first_seen_at: nil).where('total_evaluations > ?',0).count
    @revisions_last_day_lagging = @assignment.answers.where("created_at > ? and previous_version_id is NOT NULL", Time.now-1.day).count
    @revisions_with_useful_feedback = @assignment.answers.where(useful_feedback: true, review_completed: true).where("created_at > ? and previous_version_id is NOT NULL", Time.now-1.day).count

    @top_reviewers_lagged = Review.where(assignment: @assignment).where('completed_at > ?', Time.now-1.day).group(:user_id).count.sort_by {|k,v| -v }[0..4].map {|u,v| [User.find(u),v]}
    @top_reviewers = Review.where(assignment: @assignment).group(:user_id).count.sort_by {|k,v| -v }[0..4].map {|u,v| [User.find(u),v]}
    @unreviewed_right_now = @assignment.answers.where(submitted: true, total_evaluations: 0, active: true, review_completed:false).count
    @unreviewed_answers = @assignment.answers.where(submitted: true, total_evaluations: 0, active: true, review_completed:false).order('submitted_at asc')
    @submissions_total_submitted = @assignment.answers(submitted: true).count
    @total_users_submitted = @assignment.answers(submitted: true).select(:user_id).distinct.count

    if @total_users_submitted <= 300
      # Add individual student stats
      @students = @assignment.course.students
      @review_count = Review.where(assignment: @assignment, active: true).group(:user_id).count
      @submitted_answers = Answer.where(assignment: @assignment, submitted: true).group(:user_id).count

      @admins = @assignment.course.instructors
      @reviews_by_instructors = Review.where(assignment_id: @assignment.id, user_id: @admins, active: true).select(:answer_id).distinct.pluck(:answer_id)
      @unreviewed_by_staff = @assignment.answers.where(submitted: true, is_final: true).count - @reviews_by_instructors.count

      @grades = AssignmentGrade.where(assignment: @assignment, is_final: true, experimental: false).group(:user_id).sum(:credit)
    end

    render layout: "one_column"
  end

  def grades
    if current_user.instructor_for?(@assignment.course)
      @permitted_user = params[:user].nil? ? current_user : User.find(params.require(:user))
    else
      redirect_to @assignment and return unless @assignment.grades_released?
      @permitted_user = current_user
    end
    @grades = AssignmentGrade.where(assignment: @assignment, user: @permitted_user, is_final:true, experimental:false)
    render layout: "one_column"
  end

  def update_grade
    @grade = AssignmentGrade.find(params[:grade_id])
    if(@grade.update(params.require(:assignment_grade).permit(:credit,:grade_type).merge(overridden:true)))
      redirect_to grades_assignment_path(@grade.assignment, user: @grade.user), notice: "Grade updated"
    else
      redirect_to grades_assignment_path(@grade.assignment, user: @grade.user), alert: "Could not update grade"
    end
  end

  def export_grades
    respond_to do |format|
      format.csv { send_data AssignmentGrade.where(assignment_id: @assignment.id).export_to_csv, :filename => "gradebook.csv"}
    end
  end

  def resolve_action_item
    @action_item = ActionItem.find(params.permit(:item)[:item])

    @action_item.resolved = !@action_item.resolved?

    if @action_item.save
      respond_to do |format|
        format.html { redirect_to stats_assignment_path(@assignment) }
        format.js
      end
    end
  end

def review_first
    @trigger = TriggerAction.pending_action("review_required", current_user, @assignment)

    unless params[:recent_review].nil?
      @recent_review = Review.find(params[:recent_review])
    end
    #otherwise render
    if current_user.instructor_for?(@assignment.course)
      @admins = @assignment.course.instructors
      @reviewed_by_staff = Review.where(assignment_id: @assignment.id, user_id: @admins, active: true).select(:answer_id).distinct.pluck(:answer_id)
      @next_staff_submission = @assignment.answers.where(submitted: true, is_final: true).where.not(id: @reviewed_by_staff).first
    end
    render layout: "one_column"
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_assignment
      @assignment = Assignment.find(params[:id])
    end

    def set_course
      @course = Course.find(params[:course_id])
    end

    def set_breadcrumb_link
      @navbar_links ||= []
      @navbar_links << "<a href='#{assignment_path}'>Assignment</a>"
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def assignment_params
      params.permit(:course_id)
      params.permit(:grade_id)
      params.permit(:assignment_grade => [:credit])
      params.permit(:recent_review)
      params.permit(:page)
      params.require(:assignment).permit(:title, :description, :template, :example, :milestone_list, :due_at, :open_at,
        :review_due_at,
        :rubric_items_attributes=>[
          :id, :title, :short_title, :show_for_feedback, :show_for_final,
          :like_feedback_prompt,

app/helpers/assignments_helper.rb
module AssignmentsHelper
end

app/views/assignments/_more_stats.html.erb
<% grades = (AssignmentGrade.where(assignment: @assignment).group(:user_id).sum(:credit)) 
	grades = Hash[*grades.map {|user, grade| [user,grade.round]}.flatten] 
	review_by_type = Review.where(assignment_id: @assignment.id, active: true).group(:user_id, :review_type).select(:user_id, :review_type).count
	review_by_answer = Review.where(assignment_id: @assignment.id, active: true).group(:answer_id).select(:answer_id).count

	answers = {}
	@milestones.each do |m|
		answers[m] = Answer.tagged_with(m).where(active: true, assignment_id: @assignment.id).select('answers.id','user_id')
	end

	paired_reviews_copiloted = Review.where(assignment_id: @assignment.id, active: true, review_type: "paired").group(:copilot_email).count
%>

<h2>What needs your attention?</h2>

<table class="table">
	<thead>
		<tr>
			<th>Fixed</th>
			<th>Affected student</th>
			<th>Action required</th>
			<th>Actions</th>
		</tr>
	</thead>
	<tbody>
		<% @action_items.group_by(&:reason_code).each do |reason_code, items| %>
			<% case reason_code 
				 when "TOO_FEW_REVIEWS" %>
				 <tr class="info"><td colspan="4">Too few reviews</td></tr>
				 <% when "BLANK_REVIEW" %>
				 <tr class="info"><td colspan="4">Review was blank</td></tr>
				 <% when "BAD_REVIEW" %>
				 <tr class="info"><td colspan="4">Review was rated poorly</td>
				 <% when "POOR_AGREEMENT" %>
				 <tr class="info"><td colspan="4">Poor inter-rater agreement. This usually suggests that students don't have a consensus about what this question asks about.</td>
				 </tr>
			<% end %>
			<% items.each do |a| %>

				<tr <%= "class=faded" if a.resolved? %> id=<%= "action-item-#{a.id}"%>>
					<td><%= check_box_tag 'resolved', a.resolved?, a.resolved?,
							data: {remote: true, method: :post,
									url: resolve_action_item_assignment_path(@assignment, item: a.id) }
					 %></td>
					<td>
						<% if a.user.blank? %>
							Everyone
						<% else %>
						<%= a.user.name %> (<%= a.user.email %>) </td>
						<% end %>
						<% case a.reason_code 
						 when "TOO_FEW_REVIEWS" %>
						 <td><%= a.reason %></td>
						 <td>
							<%= link_to "Submission", edit_answer_path(a.answer) %> | <%= link_to "Regrade", grades_assignment_path(@assignment, user: a.user_id) %>
						 </td>
						<% when "BLANK_REVIEW" %>
							<td>Review by <%= a.review.user.name %> (<%= a.review.user.email %>). This assignment has a total of <%= review_by_answer[a.answer.id]%> reviews. </td>
							<td><%= link_to "Edit review", edit_review_path(a.review) %></td>
						<% when "BAD_REVIEW" %> 
							<td><p>Review by <%= a.review.user.name %> (<%= a.review.user.email %>).</p> <p>The reviewed student wrote: <%= truncate a.review.other_rating_comments,:length => 200, :separator => ' ' %></p></td>
							<td><%= link_to "See/Rate review", rate_review_path(a.review) %></td>
						<% when "POOR_AGREEMENT" %>
							<td><p><%= a.reason %></td>
							<td><%= link_to "Edit assignment", edit_assignment_path(@assignment) %></td>
						<% end %>
					</td>
				</tr>
			<% end %>
		<% end %>
	</tbody>
</table>

<h2>Class stats</h2>
<table class="table">
	<thead>
		<tr>
			<th>Student name</th>
			<th>Reviews performed: Exchange</th>
			<th>Paired</th>
			<th>Final</th>

			<% @milestones.each do |m| %>
				<th><%= m %> </th>
			<% end %>
			<th>Grade</th>
		</tr>
	</thead>
	<tbody>

		<% @students.order('name').each do |s| %>
			<tr>
				<td><%= s.name %> (<%= s.email %>)</td>
				<% exchange_reviews_count = review_by_type[[s.id, "exchange"]] %>
				<% if exchange_reviews_count.nil? or (exchange_reviews_count == 0) %>
					<td style="background-color: rgb(244,109,67);">
					None</td>
				<% else %>
					<td><%= exchange_reviews_count %></td>
				<% end %>
				<% paired_reviews_count =  (review_by_type[[s.id, "paired"]] or 0) + (paired_reviews_copiloted[s.email] or 0) %>
				<% if paired_reviews_count == 0 %>
					<td style="background-color: rgb(244,109,67);">
					None</td>
				<% else %>
					<td><%= paired_reviews_count %></td>
				<% end %>
				<% final_reviews_count = review_by_type[[s.id, "final"]]  %>
				<% if final_reviews_count.nil? or final_reviews_count == 0 %>
					<td style="background-color: rgb(244,109,67);">
					None</td>
				<% else %>
					<td><%= final_reviews_count %></td>
				<% end %>

				<% @milestones.each do |m| %>
				<% answer = (answers[m].select {|answer| answer.user_id == s.id}).first
			
				%>
					<% if answer.nil? %>
					<td style="background-color: rgb(244,109,67);">Not Submitted</td>
					<% else %>
						<% if review_by_answer[answer.id].nil? or review_by_answer[answer.id] == 0 %>
							<td style="background-color: rgb(255,255,191);"><%= link_to "Submitted", answer_reviews_path(answer)%>; No reviews</td>
						<% else %>
							<td style="background-color: #8cc665;"><%= link_to "Submitted", answer_reviews_path(answer)%>; <%= review_by_answer[answer.id] %> reviews</td>
						<% end %>
					<% end %>
				</td>
				<% end %>
				<td><%= grades[s.id] %> <%= link_to "Regrade", grades_assignment_path(@assignment, user: s.id) %></td>
			</tr>
		<% end %>
	</tbody>
</table>

<h2>Export</h2>
<%= link_to "Download gradebook", export_grades_assignment_path(@assignment, format: "csv"), class: "btn" %>

app/views/assignments/edit.html.erb
<%= render 'form' %>

app/views/assignments/show.html.erb
<h1>
  <%= @assignment.title %>
  <small>
    <% if @assignment.ended?%>
    Closed
    <% else %>
    Due on <%= (@assignment.due_at).strftime "%b %e, %l:%M %p" %>
    <% end %>
  </small>
</p>
</h1>
<div class="row-fluid header-buttons">

  <!-- The basic UI here is two big fat buttons, and a subsidiary menu for the lawyers -->
  <div class="col-xs-6">
    <%= link_to new_assignment_answer_path(@assignment), class:"btn paper paper-curl-right btn-block", id: "write", data: {:"show-late-warning" => @assignment.ended?} do %> Create/edit your draft <div class="deadline"> (Due <%= "in " if @assignment.due_at > Time.now %><%= distance_of_time_in_words @assignment.due_at, Time.now %><%= " ago" if @assignment.due_at < Time.now %>)</div>
    <% end %>
  </div>
  <div class="col-xs-5">
    <% show_late_warning = @assignment.review_due_at.blank? ? @assignment.ended? : @assignment.review_due_at < Time.now %>
    <%= link_to create_typed_review_assignment_path(assignment_id:@assignment,typed_review:{type:"final", revision:"Final Draft"}), method: :post, class:"btn paper paper-curl-left btn-block", id: "give-feedback", data: {:"show-late-warning" => (show_late_warning) } do %>
    Give peers feedback
    <% end %>
  </div>
  <div class="btn-group col-xs-1">
    <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">More<span class="caret"></span>
    </button>
    <ul class="dropdown-menu" role="menu">
      <li><a href="#my_answers">Cancel reviews for my draft</a></li>
      <li><a href="#my_reviews">Edit my reviews</a></li>
      <div class="divider"></div>
      <% if user_signed_in? && current_user.instructor_for?(@assignment.course) %>
        <li><%= link_to 'Edit assignment', edit_assignment_path(@assignment) %></li>
        <li><%= link_to 'Assignment statistics', stats_assignment_path(@assignment) %></li>
      <% end %>
    </ul>
  </div>
</div>
<div class="clearfix"></div>
<% if !@assignment.ended? and user_signed_in? and current_user.get_and_store_experimental_condition!(@assignment.course) != "batched_email" %>
 <%= render partial: "courses/reviewing_delay", locals:{assignment: @assignment} %>
<% end %>

<div class="row-fluid">

  <% if @my_answers.blank? %>
    <div id="assignment_description">
      <%= sanitize @assignment.description %>
    </div>
  <% end %>
  <div id="assignment_answers">
    <ul class="nav nav-tabs">
      <li class="active"><a href="#my_answers" data-toggle="tab">My Drafts</a></li>
      <li><a href="#my_reviews" data-toggle="tab">My reviews</a></li>
      <% if user_signed_in? and current_user.instructor_for?(@assignment.course) %>
      <li><a href="#out_of_box_answers" data-toggle="tab">Exceptional answers</a></li>
      <% end %>
      <% if @assignment.ended? %>
      <li><a href="#all_answers" data-toggle="tab">All answers</a></li>
      <li><a href="#starred_answers" data-toggle="tab">Starred answers</a></li>
      <% end %>
    </ul>
    <div class="tab-content">
        <div id="my_answers" class="tab-pane active">
          <% if !user_signed_in? %>
            <p>You must <%= link_to "sign in", new_user_session_path %> to see your submissions.</p>
          <% else %>
            <table class="table">
              <thead>
                <tr>
                  <th>Preview</th>
                  <th>Actions</th>
                </tr>
              </thead>
              <tbody>
                <% if @my_answers %>
                <% has_final = !@my_answers.where(is_final: true).empty? %>
                  <% @my_answers.each do |answer| %>
                  <tr>
                    <td><%= sanitize truncate(answer.response, length:50, escape: false) or "<em>Not found</em>" %></td>
                      <td>
                      <% if answer.submitted? %>
                        <% if answer.review_completed? %>
                          <span class="label label-info">No longer reviewed</span>
                        <% else %>
                          <span class="label label-success">Being reviewed</span>
                        <% end %>
                        <% if answer.is_final? %><span class="label label-danger">Submitted for final</span><% end %>
                      <% if answer.is_final? %>
                        <%= link_to "See reviews", answer_reviews_path(answer) %>
                      <% else %>
                        <%= link_to "See reviews/revise submission", answer_reviews_path(answer) %>
                         <% unless has_final %>
                          |
                        <%= link_to "Submit draft as final", upgrade_answer_path(answer), method: :post, class: "btn btn-danger btn-xs", confirm: "Are you sure you want to submit *this* draft as your final? You cannot undo this action." %>
                        <% end %>
                      <% end %>

                      <% else %>
                        <span class="label label-warning">Editing</span>
                        <%= link_to "Edit", edit_answer_path(answer), class:"btn" %> <%= link_to 'Delete draft', answer, method: :delete, data: { confirm: 'Are you sure? You can\'t undo this' } %>
                      <% end %>
                    </td>

                  </tr>
                  <% end %>
                <% end %>
              </tbody>
            </table>
            <% next_due_milestone = @assignment.task_list.detect {|task| task[:open_at] < Time.now and task[:close_at] > Time.now} %>
            <% if !next_due_milestone.blank? and @my_answers.tagged_with(next_due_milestone[:name]).blank? %>
              <p  style="text-align:center; padding:10px 0 10px 0"><%= link_to "Create your #{next_due_milestone[:name]}", new_assignment_answer_path(@assignment, draft_type: next_due_milestone[:name]), :class=>"btn btn-success" %></p>
            <% end %>
          <% end %>
        </div>
        <div id="my_reviews" class="tab-pane">
          <% if !user_signed_in?%>
          You must sign in to give feedback.
          <% else %>
          <h3>Reviews of my work</h3>
          <table class="table">
            <thead>
              <tr>
                <th>Preview</th>
                <th>Status</th>
                <th>Actions</th>
              </tr>
            </thead>
            <tbody>
              <% if @my_reviews %>
                <% @my_reviews.each do |review| %>
                <tr>

                  <td><%= sanitize truncate(review.answer.response, length:50, escape: false) or "<em>Not found</em>" %></td>
                  <% if review.rating_completed? %>
                    <td><span class="label label-success">Rating complete</span></td>
                  <% else %>
                    <td><span class="label label-warning">Unrated</span></td>
                  <% end %>
                  <td>
                  <%= link_to "Read and Rate", rate_review_path(review), class:"btn btn-primary" %>
                </td>
                </tr>
                <% end %>
              <% end %>
            </tbody>
          </table>
          <h3>Reviews I wrote</h3>
          <table class="table">
            <thead>
              <tr>
                <th>Answer preview</th>
                <th>Actions</th>
              </tr>
            </thead>
            <tbody>

              <% if !@reviews_by_me.blank? %>
                <% @reviews_by_me.each do |review| %>
                <tr>
                  <td><%= sanitize truncate(review.answer.response, length:50, escape: false) or "<em>Not found</em>" %></td>
                  <td>
                      <%= link_to "Edit", edit_review_path(review), class:"btn" %> <%= link_to 'Delete review', review, method: :delete, data: { confirm: 'Are you sure? You can\'t undo this' } %>
                  </td>
                </tr>
                <% end %>
              <% end %>
            </tbody>
          </table>
          <% end %>
        </div>
        <% if user_signed_in? and current_user.instructor_for?(@assignment.course) %>
          <div id="out_of_box_answers" class="tab-pane">
            <%= render partial: "reviews/answers_with_reviews", locals: {answers: Answer.find(@out_of_box_answers.keys)} %>
          </div>
        <% end %>
        <% if @assignment.ended?%>
        <div id="all_answers" class="tab-pane">
          <%= render partial: "reviews/answers_with_reviews", locals: {answers: @all_answers} %>
          <p  style="text-align:center; padding:10px 0 10px 0"><%= link_to "Show more answers", show_all_answers_assignment_path(@assignment), class: "btn btn-primary", remote: true %></p>
        </div>
        <div id="starred_answers" class="tab-pane">
          <%= render partial: "reviews/answers_with_reviews", locals: {answers: @starred_answers} %>
        </div>
        <% end %>
    </div>
  </div>
    <% if !@my_answers.blank? %>
    <div id="assignment_description">
      <h3>Assignment Description</h3>
      <%= sanitize @assignment.description %>
    </div>
  <% end %>
</div>

<% content_for(:modals) do %>
  <div class="modal" id="submit-late-work">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h4 class="modal-title">You're submitting after the deadline!</h4>
        </div>
        <div class="modal-body">
          <p> Submitting work after the deadline will inform staff!</p>
        </div>
        <div class="modal-footer">
          <%= link_to "Create draft anyway", new_assignment_answer_path(@assignment), class: "btn btn-default"%>
          <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
        </div>
      </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
  </div><!-- /.modal -->
  <div class="modal" id="review-late-work">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h4 class="modal-title">You're reviewing after the deadline!</h4>
        </div>
        <div class="modal-body">
          <p> Reviewing work after the deadline will inform staff!</p>
        </div>
        <div class="modal-footer">
          <%= link_to "Review anyway", create_typed_review_assignment_path(assignment_id:@assignment,typed_review:{type:"final", revision:"Final Draft"}), method: :post, class: "btn btn-default"%>
          <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
        </div>
      </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
  </div><!-- /.modal -->
<% end %>