config/routes.rb
Humanmachine::Application.routes.draw do
  Rails.application.routes.default_url_options[:protocol]="https"
  get "welcome/index"
  get "welcome/contact"
  get "welcome/tos"
  get "uploads/create"
  get "uploads/authenticate_asset" => "uploads#authenticate_asset"

  resources :courses do
    resources :assignments, shallow: true
    collection do
      get 'help'
      get 'about'
    end
    member do
      post 'regenerate_consumer_secret'
      post 'enroll_lti'
      post 'make_instructor'
      get 'instructor_list'
    end
  end

  resources :assignments do
    resources :answers, shallow: true
    member do
      get 'stats'
      get 'grades'
      get 'export_grades'
      post 'update_grade/:grade_id' => "assignments#update_grade", as: :update_grade
      post 'resolve' => 'assignments#resolve_action_item', as: :resolve_action_item
      get "show_all_answers"
      get 'review_first'
      post 'create_typed_review' => 'reviews#create_with_type'
      get 'waitlist'
      get 'flipbook'
      post 'regrade'
    end
  end

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", :registrations => "registrations" }

  devise_scope :user do
    get 'users/start' => 'registrations#start_openid', :as => :start_openid_registration
    post 'users/complete' => 'registrations#complete_openid', :as => :complete_openid_registration
    get 'users/impersonate' => 'registrations#impersonate', :as=>:impersonate_user
    post 'users/upload' => 'registrations#upload', as: :upload_users
    get 'users/import' => 'registrations#import'
    get 'sessions/toggle' => 'application#toggle_view_mode', as: :toggle_view_mode
  end

  resources :answers do
    collection do
      get 'import'
      post 'upload'
    end
    member do
      post 'upload_attachment'
      post 'direct_upload_attachment'
      delete 'delete_attachment'
      get 'star' => 'answers#star'
      get 'submit_for_feedback' => 'answers#feedback_preferences'
      post 'submit_for_feedback'
      post 'unsubmit_for_feedback'
      post 'submit_for_grades'
      post 'unsubmit_for_grades'
      get 'reflect'
      post 'clone'
      post 'upgrade'
    end
    resources :reviews, shallow: true
  end

  get 'reviews/:id/rate' => "reviews#rate", as: :rate_review
  post 'reviews/:id/rate' => "reviews#create_rating", as: :create_rate_review
  post 'reviews/:id/blank' => "reviews#report_blank", as: :report_blank_answer
  post 'reviews/:answer_id/review_answer' => "reviews#review_answer", as: :review_answer

  resources :questions do
  end

  resources :rubric_items do
    resources :answer_attributes, shallow: true
  end

  authenticated do
    root :to => 'courses#index', as: :authenticated
  end
  root :to => 'welcome#index'

  post "connect/assignments/:id" => "lti#enroll_in_assignment", as: :lti_enrollment
  get "connect/complete/:id" => "lti#complete_enrollment", as: :complete_lti_enrollment
  get "connect/test" => "lti#test"
  get "connect/guide/:id" => "lti#guide"

end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :set_answer, only: [:show, :edit, :update, :destroy,:star,
    :submit_for_feedback, :submit_for_grades, :unsubmit_for_feedback, :unsubmit_for_grades,
    :feedback_preferences,
    :reflect, :clone]
  before_action :set_assignment, only: [:new]
  before_filter :authenticate_user!
  # GET /answers
  # GET /answers.json
  def index
    redirect_to root_path and return unless current_user.admin? #FIXME Make this it is visible to instructors
    @answers = Answer.where('assignment_id = ? and active =?', params[:assignment_id], true).order('user_id').order('created_at DESC').paginate(:page => params[:page])
  end

  # GET /answers/1
  # GET /answers/1.json
  def show
    respond_to do |format|
      format.html {redirect_to root_path}
      format.text {render text: @answer.response}
    end
  end

  # GET /answers/new
  def new

    current_user.tried_answering = true
    current_user.save!
    @latest_answer = Answer.where(assignment: @assignment, user: current_user, review_completed: false).order('created_at desc').first

    if !@latest_answer.nil?
      if !@latest_answer.submitted?
        redirect_to edit_answer_path(@latest_answer), notice: "We took you to the draft you were already editing" and return
      else
        redirect_to answer_reviews_path(@latest_answer), notice: "Here are the reviews on your last submitted submission. If you have enough feedback, click 'Stop Reviewing'." and return
      end
    end
    #else
    #if in waitlist, don't allow to create
    if current_user.get_and_store_experimental_condition!(@assignment.course) == "waitlist"
      redirect_to waitlist_assignment_path(@assignment) and return
    end

    @latest_answer_review_completed = Answer.where(assignment: @assignment, user: current_user, review_completed: true).order('updated_at desc').first
    if @latest_answer_review_completed.nil?
      @answer = Answer.new
      @answer.assignment = @assignment
      @answer.active = false
      @answer.user = current_user
      @answer.response = @assignment.template unless @assignment.template.blank?
    else
      redirect_to reflect_answer_path(@latest_answer_review_completed) and return
    end
    assignment = Assignment.find(params[:assignment_id])
    if assignment.course.students.exists?(current_user.id).nil?
      assignment.course.students << current_user
    end
    draft_type = params[:draft_type].nil? ? "Final Draft" : params.require(:draft_type)
    @answer.revision_list = draft_type
    if @answer.save
      redirect_to edit_answer_path(@answer)
    else
      redirect_to root_path, alert: "We couldn't create an answer now. Please try again, or report a bug."
    end
  end

  # GET /answers/1/edit
  def edit
    unless @answer.user == current_user or current_user.instructor_for?(@answer.assignment.course)
      redirect_to assignment_path(@answer.assignment), alert: "You can only edit your own answers!" and return
    end
    @trigger = TriggerAction.pending_action("review_required", current_user, @answer.assignment)
  end
  # POST /answers
  # POST /answers.json
  def create
    @answer = Answer.new(answer_params)
    @answer.assignment = Assignment.find(params[:assignment_id])
    @answer.user = current_user

    respond_to do |format|
      if @answer.save
        format.html { redirect_to (@answer.assignment or @answer), notice: 'Answer was successfully created.' }
        format.json { render action: 'show', status: :created, location: @answer }
        format.js
      else
        format.html { render action: 'new' }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end

  # PATCH/PUT /answers/1
  # PATCH/PUT /answers/1.json
  def update
    unless @answer.user == current_user or current_user.instructor_for?(@answer.assignment.course)
      redirect_to assignment_path(@answer.assignment), alert: "You can only edit your own answers!" and return
    end

    if @answer.submitted?
      redirect_to @answer.assignment, alert: "You submitted this answer for a review, so you can't change it anymore." and return
    end
    respond_to do |format|
      if @answer.update(answer_params.merge(active: true)) #set active to true so the answer shows up everywhere
        format.html { redirect_to (@answer), notice: 'Answer was successfully updated.' }
        format.json { head :no_content }
        format.js
      else
        format.html { render action: 'edit' }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
        format.js {flash[:alert] = @answer.errors.full_messages.join(","); render}
      end
    end
  end

  # DELETE /answers/1
  # DELETE /answers/1.json
  def destroy
    @assignment = @answer.assignment
    @answer.destroy
    respond_to do |format|
      format.html { redirect_to @assignment }
      format.json { head :no_content }
    end
  end

  def submit_for_feedback
    @answer.submitted = true
    @answer.submitted_at = Time.now
    trigger = TriggerAction.add_trigger(current_user, @answer.assignment, trigger: "review_required", count: 2)
    respond_to do |format|
      if @answer.update(answer_params.merge(active: true)) and @answer.save and trigger.save
        format.html {redirect_to review_first_assignment_path(@answer.assignment)}
        format.json { head :no_content }
        format.js
      else
        format.html {redirect_to answer_path(@answer), alert: "We couldn't submit your assignment because " + @answer.errors.full_messages.join(". ")}
        format.json { render json: @answer.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end

  def feedback_preferences
    render layout: "one_column"
  end

  def unsubmit_for_feedback
    # @answer.submitted = false
    @answer.is_final = false
    @answer.review_completed = true
    respond_to do |format|
      if @answer.save
        trigger = TriggerAction.add_trigger(current_user, @answer.assignment, trigger: "review_required", count: -2)
        trigger.save!
        format.html {redirect_to reflect_answer_path(@answer), notice: "We'll stop asking students to review your draft now."}
        format.json { head :no_content }
        format.js
      else
        format.html {redirect_to answer_path(@answer), alert: "We couldn't reverse your submission because" + @answer.errors.full_messages.join(". ")}
        format.json { render json: @answer.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end

  def submit_for_grades
    @answer.submitted = true
    @answer.is_final = true
    @answer.submitted_at = Time.now
    trigger = TriggerAction.add_trigger(current_user, @answer.assignment, trigger: "review_required", count: 2)
    respond_to do |format|
      if @answer.save and trigger.save
        format.html {redirect_to assignment_path(@answer.assignment), notice: "Your draft was submitted to be graded"}
        format.json { head :no_content }
        format.js
      else
        format.html {redirect_to answer_path(@answer), alert: "We couldn't submit your assignment because " + @answer.errors.full_messages.join(". ")}
        format.json { render json: @answer.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end

  def unsubmit_for_grades
    authenticate_user_is_instructor!(@answer.assignment.course)
    @answer.is_final = false
    respond_to do |format|
      if @answer.save
        format.html {redirect_to stats_assignment_path(@answer.assignment), notice: "Marked submission as non-final"}
        format.json { head :no_content }
        format.js
      else
        format.html {redirect_to stats_assignment_path(@answer.assignment), alert: "We couldn't undo that because " + @answer.errors.full_messages.join(". ")}
        format.json { render json: @answer.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end
  #To import csv answers

  def upgrade
    #from submitted for early feedback to submitted for final feedback
    @answer = Answer.find(params[:id])
    @answer.submitted = true
    @answer.is_final = true
    @answer.submitted_at = Time.now
    respond_to do |format|
      if @answer.save
        format.html {redirect_to assignment_path(@answer.assignment), notice: "Your draft was submitted to be graded"}
        format.json { head :no_content }
        format.js
      else
        format.html {redirect_to answer_path(@answer), alert: "We couldn't submit your assignment because " + @answer.errors.full_messages.join(". ")}
        format.json { render json: @answer.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end

  def upload
    Answer.import(params[:file])
    redirect_to answers_path, :notice => "File imported"
  end

  def upload_attachment
    @answer = Answer.find(params[:id])
    @attachment = @answer.attached_assets.new(:asset => params[:file])

    if @attachment.save!
      respond_to do |format|
        format.html {redirect_to root_path}
        format.js {render layout: nil}
      end
    else
      redirect_to root_path
    end
  end

  def clone
    @cloned_answer = @answer.next_version
    if @cloned_answer.nil?
      @cloned_answer = Answer.new(user: current_user, assignment: @answer.assignment, previous_version: @answer,
        response: @answer.response, revision_list: @answer.revision_list,
        active: false, submitted: false)
      @cloned_answer.save!

      @answer.review_completed = true
      @answer.save!
    end

    respond_to do |format|
      if @answer.update(answer_params) #set active to true so the answer shows up everywhere
        format.html { redirect_to edit_answer_path(@cloned_answer) }
        format.json { head :no_content }
        format.js
      else
        format.html { render action: 'edit' }
        format.json { render json: @answer.errors, status: :unprocessable_entity }

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/_attachments.html.erb
<div id="attachments">
<strong>Attached files</strong><br/>
<% answer.versions.each do |version| %>
	<legend><small><%= version.revision_name %></small></legend>
	<div <%= "class=shaded" if version==answer %>>

	  <% version.attached_assets.each do |a| %>
	  	<% next if a.deleted? and (answer.user != current_user or current_user.instructor_for?(answer.assignment.course)) %>
	    <% if !a.asset.content_type.blank? and a.asset.content_type.include? "image" %>
	      <%=image_tag (a.asset.url :original), width: "200px", height: "200px" %>
	    <% else %>
	      <strong><a href="<%=a.asset.url %>" target="_blank"%><%= a.asset.original_filename %></a></strong>
	    <% end %>
	    <input type="text" class="selectAll" value="<%=a.asset.url %>">

	    <% if answer.user == current_user%>
	    	<% if a.deleted? %>
	    		<%= link_to "Undo delete", delete_attachment_answer_path(answer,{attachment_id: a.id}), remote: true, method: :delete %>
    		<% else %>
	    		<%= link_to "Delete", delete_attachment_answer_path(answer,{attachment_id: a.id}), remote: true, method: :delete %>
    		<% end %>
	    <% end %>
	    <br/>
	  <% end %>
	</div>
<% end -%>
</div>

app/views/answers/_form.html.erb
  <% if @answer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@answer.errors.count, "error") %> prohibited this answer from being saved:</h2>

      <ul>
      <% @answer.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    <% content_for :local_nav do %>
      <li><%= link_to "Show assignment instructions", @answer.assignment, target: "_blank" %></li>
    <% end -%>
  
      <% content_for :context_menu do %>
      <ul class="nav nav-tabs" role="tablist">
       <% if (@answer.assignment.id != 39 && @answer.assignment.id != 44) %>
        <li class="active"><a href="#evaluation" role="tab" data-toggle="tab">Assessment</a></li>
      <% end %>
        <li><a href="#reviews" role="tab" data-toggle="tab">Reviews</a></li>
      </ul>
      
      <% if (@answer.assignment.id != 39 && @answer.assignment.id != 44) %>
      <div class="tab-content">
        <div class="tab-pane active" id="evaluation">
          <div class="assignment-rubric-static"%>
            <ul class="rubric">
              <% @answer.assignment.rubric_items.each do |r| %>
              
              <li>
                <strong><%= r.short_title %> <%= "- not included in final grade" unless r.show_for_final? %></strong> <span class="pull-right label"><%= "(#{r.max_label})" unless r.max_label.blank?%></span><br/>
                <legend></legend>
                <%= sanitize r.title %>
                <table>
                  <% r.answer_attributes.each do |a_attr| %>
                    <tr>
                      <td style="vertical-align:top;">
                        <% if a_attr.attribute_type == "binary"%>
                        <input type="checkbox" disabled="disabled" style="margin:0 5px 0 0;"><% end %>
                      </td><td style="vertical-align:top;"><%= a_attr.description %>
                    <% unless a_attr.example.blank? %>
                      (<a href="#" class="see-example" data-example="example-<%=a_attr.id%>">See example</a>)
                      <div class="hidden" id="example-<%=a_attr.id%>">
                        <%= a_attr.example %>
                      </div>
                    <% end %>
                  </td>

                    </tr>
                  <% end %>
                </table>
              </li>
              <% end %>
            </ul>    
          </div>
        </div>
        <% end %>

        <div class="tab-pane" id="reviews">
          <% if @answer.previous_version.nil? %>

            <h3>No reviews yet.</h3> 
            <p>To get feedback on this answer, click "Get feedback on draft"</p>
          <% else %>
            <h3>Temporarily disabled, as we work on server stability.</h3>
            
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
  <div class="row-fluid">
    <% if @answer.submitted? or @answer.review_completed? %>
          <div class="alert alert-info">You submitted this answer for a review, so you can't change it anymore.</div>
          <div class="clearfix"></div>
          <%= sanitize @answer.response %>
    <% else %>
      <%= form_for([@assignment,@answer], remote: true, html: {id: "answer_form"}) do |f| %>      
        <div class="actions">
          <%= f.submit "Save Draft", class: "btn btn-default", id: "save-draft"%> <em style="color: #999;"><span class="answer-save-status">Unsaved</span></em> <span class="answer_public_status"></span> 
          <div class="navbar-right">
            <% if @answer.submitted? %>
            <%= link_to "Stop reviewing", unsubmit_for_feedback_answer_path, :class=>"btn btn-danger", :role=>"button", :method=>:post %>
            <% else %>
            <% seek_feedback_class = (@answer.assignment.due_at - Time.now > 1.day) ? "btn-primary": "btn-default" %>
              <% unless current_user.get_and_store_experimental_condition!(@answer.assignment.course) == "no_early_feedback" %>  
                <%= link_to "Get feedback on draft", submit_for_feedback_answer_path, :class=>"btn #{seek_feedback_class}", :id=>"submit-for-feedback", :role=>"button", :"data-no-turbolink" => true%> 
              <% end %>
            <% end %>
            <% unless @answer.is_final? or @answer.assignment.course.early_feedback_only? %>
             <button class="btn btn-default" id="submit-final">Submit for grading as final</button>
            <% end %>
        </div>
      </div>
      <div class="clearfix"></div>
        <%= f.text_area :response, size: "20x20", :id=>"answer_response", :class=>"editable" %>
      <% end %>
    <% end %>
</div>

<script type="text/javascript">
$().ready(function(){  $('[data-toggle=popover]').popover({trigger:'hover'});});</script>

<% content_for(:modals) do %>
<div class="modal" id="example-review-modal">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h4 class="modal-title">Here's an example submission that would score well</h4>
        </div>
        <div class="modal-body">
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Back to your work</button>
        </div>
      </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
  </div><!-- /.modal -->

  <div class="modal" id="warn-final-modal">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h4 class="modal-title">When you submit as final, you can't modify your draft</h4>
        </div>
        <div class="modal-body">
          <p>Final submissions are graded, and you can also only submit one final draft. So only submit your best work! </p>

          <p><strong>There is no undo!</strong></p>
        </div>
        <div class="modal-footer">
          <%= link_to "Submit for grading as final", submit_for_grades_answer_path, :class=>"btn btn-primary", :role=>"button", method: :post %>
          <button type="button" class="btn btn-default" data-dismiss="modal" id="cancel-submit-grade">Cancel</button>
        </div>
      </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
  </div><!-- /.modal -->
<% end %>

app/views/answers/autosubmit.js.erb
<% if @answer.in_progress? %>
$('.answer_public_status').html('Will not auto-submit on deadline. ' + '<%= j link_to "Auto-submit", autosubmit_answer_path(@answer,true), remote: true, method: :post,  data: {toggle: "popover"}, title: "You can continue to make changes till the deadline. On the deadline, you must manually submit the assignment."%>')
<% else %>
$('.answer_public_status').html('Will auto-submit on deadline. ' + '<%= j link_to "Don't auto-submit", autosubmit_answer_path(@answer,false), remote: true, method: :post,  data: {toggle: "popover"}, title: "You can continue to make changes till the deadline. On the deadline, the draft will be automatically submitted. If you don't want to submit unfinished work, choose don't auto-submit."%>')
<% end %>

$('[data-toggle=popover]').popover({trigger:'hover'});

app/views/answers/delete_attachment.js.erb
$("#attachments").html("<%= j render partial: "attachments", locals: {answer: @answer} %>")

app/views/answers/edit.html.erb
<%= render 'form' %>

app/views/answers/feedback_preferences.html.erb
<h1>What would you most like feedback on?</h1>


<div class="row-fluid">
  <div class="col-sm-12 col-md-9">
    <div class="well">
      <p>Since this is an early draft, some parts may be more "under-construction" than others. Help your classmates focus what they give you feedback on.</p>
      <h4>We recommend you say...</h4>
      <ul>
        <li>What parts of your submission do you most need help on?</li>
        <li>What parts are under construction?</li>
      </ul>
    </div>
<%= form_for @answer, url: submit_for_feedback_answer_path, method: :post do |f| %>
    <div class="form-group">
      <%= f.label :review_request, "Request for reviewers" %>
      <%= f.text_area :review_request, class:"form-control", placeholder:"Can you tell me if I am going in the right direction for..." %>
    </div>
  </div>
</div>
<div class="row-fluid">
  <div class="actions col-sm-12 col-md-9">        
    <div class="navbar-right">
      <%= link_to "Cancel reviewing", edit_answer_path, :class=>"btn btn-danger", :role=>"button" %>
      <%= f.submit "Get feedback on draft", :class=>"btn btn-success", :role=>"button" %>
    </div>
  </div>
</div>
<% end %>

app/views/answers/import.html.erb
<%= form_tag upload_answers_path, multipart: true do %>
  <%= file_field_tag :file %>
  <%= submit_tag "Import" %>
<% end %>

app/views/answers/index.html.erb
<h1>Pick the student you want to review</h1>
<table class="table">
  <thead>
    <tr>
      <th>Student name</th>
      <th>Revision Name</th>
      <th>Review</th>
    </tr>
  </thead>
  <tbody>
    <% @answers.each do |answer| %>
          <% next if answer.user.nil? %>
    <tr class="<%= 'faded' unless answer.is_latest_revision? %>">
      <td><%= answer.user.name %></td>
      <td><%= answer.revision_name %></td>
      <td>
        <% unless answer.is_latest_revision? %>
        <%= link_to "Start new review", new_answer_review_path(answer), data: { confirm: 'You are going to review an outdated draft of this submission. Are you sure?' } %>
        <% else %>
        <%= link_to "Start new review", new_answer_review_path(answer) %>
        <% end %>
        </td>
    </tr>
    <% end %> 
  </tbody>
</table>
<%= will_paginate @answers %>

app/views/answers/new.html.erb
<%= render 'form' %>

<%= link_to 'Back', answers_path %>

app/views/answers/reflect.html.erb
<%= render partial: "reviews/list_multiple", locals: {answer: @answer,feedback_items_by_rubric_item: @answer.feedback_items_by_rubric_item, show_revision_link: false} %>

<div class="page_title">
	<h1>Revise draft</h1>
</div>

<%= form_for([@assignment,@answer], remote: false, url: clone_answer_path(@answer), method: :post) do |f| %>

<div class="row-fluid">


	<div class="form-group">
		<h4>1. Overall, did you get useful feedback on your draft? <small>This information also helps us improve Peerstudio</small></h4>
    <div class="radio">
      <%= f.label :useful_feedback_true do %>
        <%= f.radio_button :useful_feedback, true, value: true -%>Yes
      <% end %>
    </div>
    <div class="radio">
     <%= f.label :useful_feedback_false do %>
      <%= f.radio_button :useful_feedback, false, value: false %> No
     <% end %>
    </div>
    
  	</div>
</div>
	<div class="hide-on-choose">
		<strong><p>Please choose Yes or No to continue</p></strong>
	</div>
  	<div class="reflect-instructions row-fluid" style="display:none;	">
		<h4>2. Ok, as you revise, remember,</h4>
		<!-- This is based on Geoff Cohen's wise feedback suggestions: http://psp.sagepub.com/content/25/10/1302.full.pdf+html -->
		<ul>
			<li>The rubrics hold you to a high standard. Meeting this standard is challenging, but it's also rewarding. </li>
			<li>By creating an early draft and asking for feedback on it, you've already demonstrated that you can meet this high standard. </li>
			<li class="feedback-useful" style="display:none;">Now, reflect on your answer, your feedback, as well as other submissions you have reviewed and think about what you want to revise. </li>
			<li class="feedback-not-useful" style="display:none;">Even if you didn't receive good feedback, you can still "self-assess", and use other submissions you have reviewed to think about what you want to revise. </li>
		</ul>
		
		<div class="row-fluid">
			<div class="form-group">
				<%= f.label :reflection, "My reflections on feedback, and what I want to revise" %>
				<%= f.text_area :reflection, class: "form-control expandable" %>

			</div>
				<%= f.submit "Save reflections and revise submission", class: "btn btn-primary" %>
			<% end %>
		</div>
	</div>
<script type="text/javascript">
	$('#answer_useful_feedback_true').click(function() {
		$('.reflect-instructions').show();
		$('.feedback-useful').show();
		$('.feedback-not-useful').hide();
		$('.hide-on-choose').hide();
	});

	$('#answer_useful_feedback_false').click(function() {
		$('.reflect-instructions').show();
		$('.feedback-useful').hide();
		$('.feedback-not-useful').show();
		$('.hide-on-choose').hide();
	});

</script>

app/views/answers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Response:</strong>
  <%= @answer.response %>
</p>

<p>
  <strong>Question:</strong>
  <%= @answer.question_id %>
</p>

<p>
  <strong>User:</strong>
  <%= @answer.user_id %>
</p>

<p>
  <strong>Predicted score:</strong>
  <%= @answer.predicted_score %>
</p>

<p>
  <strong>Current score:</strong>
  <%= @answer.current_score %>
</p>

<p>
  <strong>Evaluations wanted:</strong>
  <%= @answer.evaluations_wanted %>
</p>

<p>
  <strong>Total evaluations:</strong>
  <%= @answer.total_evaluations %>
</p>

<p>
  <strong>Confidence:</strong>
  <%= @answer.confidence %>
</p>

<%= link_to 'Edit', edit_answer_path(@answer) %> |
<%= link_to 'Back', answers_path %>

app/views/answers/star.js.erb
<% if @answer.starred? %>
	$(".star_answer").text("Answer starred")
<% else %>
	$(".star_answer").text("Star answer")
<% end %>

app/views/answers/update.js.erb
$(".answer-save-status").removeClass("label-danger").removeClass("label-warning").text('Saved')

app/views/answers/upload_attachment.js.erb
$(".pendingUpload").text("Upload complete")
$("#attachments").html("<%= j render partial: "attachments", locals: {answer: @answer} %>")