config/routes.rb
Humanmachine::Application.routes.draw do
  Rails.application.routes.default_url_options[:protocol]="https"
  get "welcome/index"
  get "welcome/contact"
  get "welcome/tos"
  get "uploads/create"
  get "uploads/authenticate_asset" => "uploads#authenticate_asset"

  resources :courses do
    resources :assignments, shallow: true
    collection do
      get 'help'
      get 'about'
    end
    member do
      post 'regenerate_consumer_secret'
      post 'enroll_lti'
      post 'make_instructor'
      get 'instructor_list'
    end
  end

  resources :assignments do
    resources :answers, shallow: true
    member do
      get 'stats'
      get 'grades'
      get 'export_grades'
      post 'update_grade/:grade_id' => "assignments#update_grade", as: :update_grade
      post 'resolve' => 'assignments#resolve_action_item', as: :resolve_action_item
      get "show_all_answers"
      get 'review_first'
      post 'create_typed_review' => 'reviews#create_with_type'
      get 'waitlist'
      get 'flipbook'
      post 'regrade'
    end
  end

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", :registrations => "registrations" }

  devise_scope :user do
    get 'users/start' => 'registrations#start_openid', :as => :start_openid_registration
    post 'users/complete' => 'registrations#complete_openid', :as => :complete_openid_registration
    get 'users/impersonate' => 'registrations#impersonate', :as=>:impersonate_user
    post 'users/upload' => 'registrations#upload', as: :upload_users
    get 'users/import' => 'registrations#import'
    get 'sessions/toggle' => 'application#toggle_view_mode', as: :toggle_view_mode
  end

  resources :answers do
    collection do
      get 'import'
      post 'upload'
    end
    member do
      post 'upload_attachment'
      post 'direct_upload_attachment'
      delete 'delete_attachment'
      get 'star' => 'answers#star'
      get 'submit_for_feedback' => 'answers#feedback_preferences'
      post 'submit_for_feedback'
      post 'unsubmit_for_feedback'
      post 'submit_for_grades'
      post 'unsubmit_for_grades'
      get 'reflect'
      post 'clone'
      post 'upgrade'
    end
    resources :reviews, shallow: true
  end

  get 'reviews/:id/rate' => "reviews#rate", as: :rate_review
  post 'reviews/:id/rate' => "reviews#create_rating", as: :create_rate_review
  post 'reviews/:id/blank' => "reviews#report_blank", as: :report_blank_answer
  post 'reviews/:answer_id/review_answer' => "reviews#review_answer", as: :review_answer

  resources :questions do
  end

  resources :rubric_items do
    resources :answer_attributes, shallow: true
  end

  authenticated do
    root :to => 'courses#index', as: :authenticated
  end
  root :to => 'welcome#index'

  post "connect/assignments/:id" => "lti#enroll_in_assignment", as: :lti_enrollment
  get "connect/complete/:id" => "lti#complete_enrollment", as: :complete_lti_enrollment
  get "connect/test" => "lti#test"
  get "connect/guide/:id" => "lti#guide"

end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  # before_filter authenticate_user! except: :index
  before_filter :authenticate_user_is_admin!, only: [:new, :create]

  before_action :set_course, only: [:show, :edit, :update, :destroy, :regenerate_consumer_secret, :enroll_lti, :make_instructor, :instructor_list]
  before_filter :authenticate_user_is_instructor_for_this_course!, only: [:edit, :update, :destroy, :regenerate_consumer_secret, :make_instructor, :instructor_list]
  skip_before_filter :verify_authenticity_token, :only => [:enroll_lti]

  layout "one_column"

  # GET /courses
  # GET /courses.json
  def index
    @courses = Course.where(hidden: false).order('created_at desc')
  end

  # GET /courses/1
  # GET /courses/1.json
  def show
    @closest_assign = @course.closest_open(params[:id])
  end

  # GET /courses/new
  def new
    @course = Course.new(user: current_user)
  end

  # GET /courses/1/edit
  def edit
  end


  def instructor_list
    @admins = User.where(admin: true) #Show the admins in the system, to easily add them as instructors
  end
  #POST make_instructor
  def make_instructor
    authenticate_user_is_instructor!(@course)

    @new_instructor = User.find_for_authentication(email: params[:instructor_email])
    if @new_instructor.nil?
      redirect_to instructor_list_course_path(@course), alert: "No user with that email." and return
    end
    if @course.make_instructor(@new_instructor)
      redirect_to instructor_list_course_path(@course), notice: "Added new instructor"
    end
  end


  # POST /courses
  # POST /courses.json
  def create
    @course = Course.new(course_params)
    @course.user = current_user

    respond_to do |format|
      if @course.save
        format.html { redirect_to @course, notice: 'Course was successfully created.' }
        format.json { render action: 'show', status: :created, location: @course }
      else
        format.html { render action: 'new' }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /courses/1
  # PATCH/PUT /courses/1.json
  def update
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to @course, notice: 'Course was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit', alert: 'There was trouble saving your changes.' }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1
  # DELETE /courses/1.json
  def destroy
    @course.destroy
    respond_to do |format|
      format.html { redirect_to courses_url }
      format.json { head :no_content }
    end
  end

  def about
    render layout: "one_column"
  end

  def regenerate_consumer_secret
    @course.regenerate_consumer_secret!
    redirect_to edit_course_path(@course)
  end

  def enroll_lti
    raise params.inspect
    user = @course.enroll_with_lti(request)
    if user
      sign_in(:user, user)
      if user.consented.nil?
        redirect_to @course, notice: "TODO Consent"
      else

        redirect_to @course, notice: "Enrollment successful"
      end
    else
      raise params.inspect
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_course
      @course = Course.find(params[:id])
    end

    def authenticate_user_is_instructor_for_this_course!
      authenticate_user_is_instructor!(@course)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def course_params
      params.require(:course).permit(:title, :institution, :hidden, :open_enrollment, :user_id, :photo,
        :instructor_name, :early_feedback_only, :show_timer, :waitlist_condition,
        :consumer_key,
        #All the LTI params
        :tool_consumer_info_product_family_code,
        :oauth_signature_method,
        :lis_outcome_service_url,
        :tool_consumer_info_version,
        :oauth_signature,
        :resource_link_title,
        :lti_message_type,
        :lis_result_sourcedid,
        :lis_person_name_full,
        :context_label,
        :oauth_consumer_key,
        :user_id,
        :oauth_version,
        :resource_link_id,
        :oauth_callback,
        :lis_person_contact_email_primary,
        :roles,
        :launch_presentation_locale,
        :context_title,
        :tool_consumer_instance_guid,
        :oauth_timestamp,
        :lti_version,
        :ext_basiclti_submit,
        :context_id,
        :oauth_nonce,
        :tool_consumer_instance_description,
        :id)
    end
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/views/courses/_course_box.html.erb
<li class="<%= " faded" if course.ended? %>">
  <a <% unless course.ended? %> href="<%=course_path(course) %>" <% end %> class="thumbnail" style="padding: 0; height: 325px; width:370px; overflow: hidden;">
    <div class="image" style="height: 140px; background-image: url(<%= course.photo.url %>); background-repeat:no-repeat; background-size:100%;"></div>
    <div style="padding: 10px;">
      <b style="line-height: 25px" class="title"><%= course.title %></b>
      <% if course.ended? %>
      	<span style="color: #3f3f3f; font-weight: 700; font-size: 14pt;">&nbsp;&nbsp;&#8212;&nbsp;&nbsp;ENDED</span>
      <% end %>
      <legend></legend>
      <table style="color:#3f3f3f">
        <tr>
          <td class="row_header">
            INSTRUCTOR
          </td>
          <td>
            <%= course.instructor_name %>
          </td>
        </tr>
        <tr>
          <td class="row_header">
            UNIVERSITY
          </td>
          <td>
            <%= course.institution %>
          </td>        
        </tr>
      </table>
    </div>
  </a>
</li>

app/views/courses/_form.html.erb
<div class="row-fluid">
  <% if @course.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@course.errors.count, "error") %> prohibited this course from being saved:</h2>

      <ul>
      <% @course.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
</div>
<div class="row-fluid">
  <%= form_for(@course) do |f| %>

  <div class="col-sm-4">
    <ul class="thumbnails" style="padding-left: 0px;">
    <style>
      .row_header {
        font-weight: 700;
        font-size: 10pt;
        text-align: right;
        padding-right: 10px;
        vertical-align: top;
      }

      .thumbnails > li {
        margin-left: 0px;
      }
    </style>

    <li class="<%= " faded" if @course.ended? %>">
      <div class="thumbnail" style="padding: 0; height: 325px; width:370px; overflow: hidden;">
        <div class="image" style="height: 140px; background-image: url(<%=@course.photo.url %>); background-repeat:no-repeat; background-size:100%;">
          <%= f.label :photo, "Change course image" %><br>
          <%= f.file_field :photo %>
        </div>
        <div style="padding: 10px;">
          <b style="line-height: 25px" class="title"><%= f.text_field :title , placeholder: "Course title"%></b>
          <% if @course.ended? %>
            <span style="color: #3f3f3f; font-weight: 700; font-size: 14pt;">&nbsp;&nbsp;&#8212;&nbsp;&nbsp;ENDED</span>
          <% end %>
          <legend></legend>
          <table style="color:#3f3f3f">
            <tr>
              <td class="row_header">
                INSTRUCTOR
              </td>
              <td>
                <%= f.text_field :instructor_name, class:"form-control", placeholder: "Courtney Noh" %>
              </td>
            </tr>
            <tr>
              <td class="row_header">
                UNIVERSITY
              </td>
              <td>
                <%= f.text_field :institution, class:"form-control", placeholder: "Stanford University" %>
              </td>
            </tr>
          </table>
        </div>
      </a>
    </li>
    </ul>
  </div>
  <div class="col-sm-6">
    <div class="checkbox">
      <%= f.label :hidden do %>
        <%= f.check_box :hidden %> <strong>This course is hidden</strong> (Don't show it on the PeerStudio homepage)
      <% end %>
    </div>

    <div class="checkbox">
      <%= f.label :show_timer do %>
        <%= f.check_box :show_timer %> <strong>Show students an estimate of reviewing delay</strong>
        <div class="well">
          <p>Preview:</p>
            <%= render partial: "reviewing_delay", locals:{assignment: nil} %>
        </div>
      <% end %>
    </div>
    <div class="checkbox">
      <%= f.label :open_enrollment do %>
        <%= f.check_box :open_enrollment %> <strong>This class is now active</strong> (students can submit work)
      <% end %>
    </div>
        <div class="checkbox">
      <%= f.label :early_feedback_only do %>
        <%= f.check_box :early_feedback_only %> <strong>Only use PeerStudio for early feedback </strong> (students submit final work elsewhere)
      <% end %>
    </div>
        <div class="checkbox">
      <%= f.label :waitlist_condition do %>
        <%= f.check_box :waitlist_condition %> <strong>This class has a waitlist for students</strong> (for research!)
      <% end %>
    </div>

    <div class="form-group">
      <%= f.label :forum_link do %>
        Help forum URL <small>(Set up a forum on your class page for peer assessment questions, and save the link here)</small>
      <%end%>
      <%= f.url_field :forum_link, class:"form-control", placeholder:"https://..." %>
    </div>
    <% if @course.persisted? %>
      <div class="form-group">
        <%= f.label :consumer_key do %>
          LTI Consumer key <small>(Use this to set up pushing grades to coursera/edx/etc.)</small>
        <%end%>
        <%= f.text_field :consumer_key, class:"form-control", placeholder:"coursera_course_title" %>
        <%= f.label :consumer_secret do %>
          LTI Consumer secret<small>(Use this to set up pushing grades to coursera/edx/etc.)</small>
        <%end%>


          <div class="row-fluid">
            <%= f.text_field :consumer_secret, class:"form-control", disabled:"disabled", placeholder:"Click regenerate to set" %>
            <% unless @course.id.nil? %>
              <%= link_to "Regenerate secret", regenerate_consumer_secret_course_path(@course), class:"btn btn-default ", method: :post %>
            <% else %>
              <%= link_to "Regenerate secret (save course first)", "#", class:"btn btn-default", disabled:"disabled" %>
            <% end %>
          </div>
      </div>
    <% end %>
    <% if @course.persisted? %>
      <p>Change who is on the <%= link_to "teaching staff", instructor_list_course_path(@course) %>.</p>
    <% else %>
      <p> Save the course to edit the teaching staff and LTI credentials. </p>
    <% end %>
    <div class="form-group">
      <%= f.submit :"class"=> "btn btn-primary" %>
    </div>
  </div>
</div>

<% end %>

app/views/courses/_reviewing_delay.html.erb
<% if assignment.nil? or assignment.course.show_timer? %>
  <h3 style="font-weight:300; display:none;" id="countdown-banner"> Submit a draft within <span id="time-left" style="color: #428bca; font-weight:bolder;">4 hours</span> and get feedback by <span id="feedback-time">10 PM</span> <span id="feedback-day">tonight</span>. <small>(You can improve your essay and submit again!)</small></h3>
<% end %>

app/views/courses/about.html.erb
<h1>About Peerstudio</h1>
<p>Peerstudio is a research project at Stanford University and UC San Diego.</p>

<p>The primary contributors are Chinmay Kulkarni, Courtney Noh, Julie Fortuna, Ed Hutchins, Scott R. Klemmer and Michael S. Bernstein.</p>

<h1>About our research</h1>
<p>Please see our <a href="http://research.peerstudio.org">research page</a> for publications and other research findings.</p>

<h1>Our sponsors</h1>
<p>Our research is made possible by the generous support of the National Science Foundation, the Siebel Scholars program, the Hasso Plattner Design Thinking Program, and friends of the Stanford HCI group. </p>

<h2>Software credits and licenses
<small>This website uses the following software components and libraries.</small></h2>

<h4>Icons and artwork</h4>
<p><a href="http://thenounproject.com/term/feedback/24834/">Feedback</a> designed by Wesley Hare from the Noun Project</p> (licenced under Creative Commons Attribution 3.0 Unported (CC BY 3.0))
<p><a href="http://thenounproject.com/term/pencil/55533/">Pencil</a> designed by Javier Sánchez - javyliu from the Noun Project (licenced under Creative Commons Attribution 3.0 Unported (CC BY 3.0))</p>
<p><a href="http://glyphicons.com/">Glyphicons</a> by http://glyphicons.com/, (licenced under Creative Commons Attribution 3.0 Unported (CC BY 3.0))</p>
<p>Bootstrap by Twitter, Inc (under the MIT license, below)</p>
<p><a href="https://www.flickr.com/photos/yourdon/4340001235/in/photostream/">Untitled</a>, by <a href="https://www.flickr.com/photos/yourdon/">Ed Yourdon</a> (licensed under Creative Commons Attribution-NonCommercial-ShareAlike 2.0 Generic)</p>
<p><a href="https://www.flickr.com/photos/maximalideal/4736067734">Bhargava explains it all</a>, by <a href="https://www.flickr.com/photos/maximalideal/">Christopher Holden</a> (licensed under Creative Commons Attribution-ShareAlike 2.0 Generic)</p>

<h2>License terms <small>Some software require us to include license terms when we use their software</small></h2>
<div class="row">
	<div class="col-sm-8 col-md-6">
		<pre>
		The MIT License (MIT)



		Permission is hereby granted, free of charge, to any person obtaining a copy
		of this software and associated documentation files (the "Software"), to deal
		in the Software without restriction, including without limitation the rights
		to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
		copies of the Software, and to permit persons to whom the Software is
		furnished to do so, subject to the following conditions:

		The above copyright notice and this permission notice shall be included in
		all copies or substantial portions of the Software.

		THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
		IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
		FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
		AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
		LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
		OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
		THE SOFTWARE.
		</pre>
	</div>
</div>

app/views/courses/edit.html.erb
<%= render 'form' %>

app/views/courses/help.html.erb
<h1><span style="color: #999;font-weight:200;">Sometimes you just need a little</span> <span style="font-weight:300;">help</span></h1>

<p>This page helps you solve technical problems you might face with PeerStudio. It doesn't help you with deadlines or course policy-- your professors and TAs remain your best resources for that.</p>

<h2>Quick fixes</h2>
<p>Here are a few quick things you can try for nearly all problems.</p>
<ul>
	<li><strong>Use a different browser</strong> If you are using an old browser, many features may not work. We recommend you use the most updated version of Chrome, Firefox or Safari. We have very limited development resources, and can't ensure the site works with Internet Explorer.</li>
	<li><strong>Are you logged in?</strong> Many actions require a login. If you're not logged in, try logging in, and see if it works. If you succeed after logging in, report a bug below. </li>
	<li><strong>Try one more time</strong> Try again, but only once or twice! This helps if the site was busy when you tried the first time. Something that doesn't work after a couple of tries is most likely a bug, so report it. Please don't keep trying-- it only makes a busy time busier. We automatically bring more machines online if we notice lots of people using the site, but this still takes time. </li>
</ul>

<h2>Known issues</h2>
<p>Are you having trouble with...</p>
<ul>
	<li><strong>File doesn't upload</strong> File upload won't work if you are using a browser older than Internet Explorer 10, Chrome 32, Safari 5.3. (No plans to fix, please upgrade)</li>
</ul>

<h2>E-mail us your problem</h2>
<p>You can reach us at <a href="mailto:peerstudio@cs.stanford.edu">peerstudio@cs.stanford.edu</a>. We will usually respond within one day. We welcome bugs, suggestions for improvement and general comments. </p>

app/views/courses/index.html.erb
<h1 id="course_header">Please select a course to begin</h1> 
<p><button id="startTourBtn" class="btn btn-large btn-primary">First time here? Take a tour of PeerStudio</button></p>
<style>
  .row_header {
    font-weight: 700;
    font-size: 10pt;
    text-align: right;
    padding-right: 10px;
    vertical-align: top;
  }

  .thumbnails > li {
    /*display: inline-block;*/
    vertical-align: top;
    margin:20px;
  }
</style>
<ul class="thumbnails" style="padding-left:0px;">
    <% @courses.each do |course| %>
      <%= render :partial => 'course_box', :locals => { :course => course } %>
    <% end %>
</ul>

app/views/courses/instructor_list.html.erb
<h1>Instructors for <em><%= @course.title %></em></h1>

<%= form_tag make_instructor_course_path(@course) do %>
<div class="form-group">
  <label for="instructor_email">Email address</label>
  <%=email_field_tag :instructor_email, "", class:"form-control", placeholder:"Enter email to add an instructor" %>
</div>
<%= submit_tag "Add instructor", class:"btn btn-default" %>
<% end %>

<p>To remove instructors from this list, please email hello@peerstudio.org. </p>
<h2>Instructors</h2>
  <ul>
  <% @course.instructors.each do |instructor| %>
    <li><%= instructor.name %> (<%= instructor.email %>)</li>
  <% end %>
  </ul>

<h2>System administrators</h2>
<p>System administrators have access to student submissions, reviews and suggested grades, so they can help students if they face problems. They cannot review as staff.</p>
  <ul>
    <% @admins.each do |admin| %>
    <li><%= admin.name %> (<%= admin.email %>)</li>
    <% end %>
  </ul>

app/views/courses/new.html.erb
<h1 style="padding-left:17px;">New course</h1>

<%= render 'form' %>

<%= link_to 'Back', courses_path %>

app/views/courses/show.html.erb
<% content_for :title do %>
  Peerstudio | <%= @course.title %>
<% end %>

<style>
  .bright {
    font-size: 1.3em;
    font-style: italic;
  }

  .closed {
    opacity:0.5;
  }
</style>

  <% if @closest_assign.nil? %>
    <h1 id="assignment_title">No assignments open at this moment.</h1>
  <% else %>
  <h1 id="assignment_title"><%= link_to @closest_assign.title, @closest_assign %>
  <small> <%=due_date(@closest_assign.due_at) %></h1>
    <% if user_signed_in? and current_user.instructor_for?(@course) %>
            <td><%= link_to 'Destroy', @closest_assign, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    <% end %>
  </small>

<div class="row-fluid header-buttons">
  <div class="row-fluid">
    <div id="assignment_description">
      <%= truncate (sanitize @closest_assign.description), length: 500, escape: false %> <%= link_to "(More)" , @closest_assign %>
    </div>
  </div>
  <div class="btn-group">
    <% if @closest_assign.due_at > Time.now %>
      <%= link_to "Write your answer", new_assignment_answer_path(@closest_assign), class: "btn btn-default" %>
    <% else %>
      You can't submit anymore, but you can review.
    <% end %>
  </div>
  <div class="btn-group">
      <%= link_to create_typed_review_assignment_path(@closest_assign, assignment_id:@closest_assign,typed_review:{type:"final", revision:"Final Draft"}), class: "btn btn-default", method: :post do %> Give peers feedback <% end %>
  </div>
  <%= render partial: "reviewing_delay", locals: {assignment: @closest_assign} %>
</div>
  <div class="clearfix"></div>
<% end %>


<div style="padding-left:20px">
<div class="row">
  <h1 id="other_assignments">Other assignments</h1>
  <table class="table">
  <thead>
    <tr>
      <th>Title</th>
      <th>Due on</th>
      <% if user_signed_in? && current_user.instructor_for?(@course) %>
      <th colspan="2"><%= link_to "Add assignment", new_course_assignment_path(@course), class: "btn btn-success"%> </th>
      <% end %>
    </tr>
  </thead>

  <tbody>
    <%= render partial: "assignments/short_show", collection:@course.assignments.where('(due_at > ? or (review_due_at is not null and review_due_at > ?)) and open_at < ?', Time.now, Time.now, Time.now).order('due_at asc').offset(1)%>
    <%= render partial: "assignments/short_show", collection:@course.assignments.where('(due_at < ? or (review_due_at is not null and review_due_at < ?)) and open_at < ?', Time.now, Time.now, Time.now).order('due_at asc')%>
    <% if user_signed_in? and current_user.instructor_for?(@course) %>
    <tr>
      <td colspan="4"><strong>Assignments below this line yet open (visible only to staff)</strong></td>
    </tr>
      <%= render partial: "assignments/short_show", collection:@course.assignments.where('open_at > ? ', Time.now).order('due_at asc')%>
    <% end %>
  </tbody>
</table>

</div>
<div class="row">
  <% if user_signed_in? && current_user.instructor_for?(@course) %>
  <p class="lead">This course is <strong><%= @course.hidden? ? "hidden from students" : "visible to students"%></strong>, and is currently <strong><%= @course.open_enrollment? ? "open" : "closed" %> </strong> for enrollment. <%= link_to '(Modify)', edit_course_path(@course) %> </p>
  <% end %>
</div>
</div>