config/routes.rb
Humanmachine::Application.routes.draw do
  Rails.application.routes.default_url_options[:protocol]="https"
  get "welcome/index"
  get "welcome/contact"
  get "welcome/tos"
  get "uploads/create"
  get "uploads/authenticate_asset" => "uploads#authenticate_asset"

  resources :courses do
    resources :assignments, shallow: true
    collection do
      get 'help'
      get 'about'
    end
    member do
      post 'regenerate_consumer_secret'
      post 'enroll_lti'
      post 'make_instructor'
      get 'instructor_list'
    end
  end

  resources :assignments do
    resources :answers, shallow: true
    member do
      get 'stats'
      get 'grades'
      get 'export_grades'
      post 'update_grade/:grade_id' => "assignments#update_grade", as: :update_grade
      post 'resolve' => 'assignments#resolve_action_item', as: :resolve_action_item
      get "show_all_answers"
      get 'review_first'
      post 'create_typed_review' => 'reviews#create_with_type'
      get 'waitlist'
      get 'flipbook'
      post 'regrade'
    end
  end

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", :registrations => "registrations" }

  devise_scope :user do
    get 'users/start' => 'registrations#start_openid', :as => :start_openid_registration
    post 'users/complete' => 'registrations#complete_openid', :as => :complete_openid_registration
    get 'users/impersonate' => 'registrations#impersonate', :as=>:impersonate_user
    post 'users/upload' => 'registrations#upload', as: :upload_users
    get 'users/import' => 'registrations#import'
    get 'sessions/toggle' => 'application#toggle_view_mode', as: :toggle_view_mode
  end

  resources :answers do
    collection do
      get 'import'
      post 'upload'
    end
    member do
      post 'upload_attachment'
      post 'direct_upload_attachment'
      delete 'delete_attachment'
      get 'star' => 'answers#star'
      get 'submit_for_feedback' => 'answers#feedback_preferences'
      post 'submit_for_feedback'
      post 'unsubmit_for_feedback'
      post 'submit_for_grades'
      post 'unsubmit_for_grades'
      get 'reflect'
      post 'clone'
      post 'upgrade'
    end
    resources :reviews, shallow: true
  end

  get 'reviews/:id/rate' => "reviews#rate", as: :rate_review
  post 'reviews/:id/rate' => "reviews#create_rating", as: :create_rate_review
  post 'reviews/:id/blank' => "reviews#report_blank", as: :report_blank_answer
  post 'reviews/:answer_id/review_answer' => "reviews#review_answer", as: :review_answer

  resources :questions do
  end

  resources :rubric_items do
    resources :answer_attributes, shallow: true
  end

  authenticated do
    root :to => 'courses#index', as: :authenticated
  end
  root :to => 'welcome#index'

  post "connect/assignments/:id" => "lti#enroll_in_assignment", as: :lti_enrollment
  get "connect/complete/:id" => "lti#complete_enrollment", as: :complete_lti_enrollment
  get "connect/test" => "lti#test"
  get "connect/guide/:id" => "lti#guide"

end

app/models/rubric_item.rb
class RubricItem < ActiveRecord::Base
  belongs_to :assignment
  belongs_to :user
  has_many :answer_attributes, :dependent => :destroy
  accepts_nested_attributes_for :answer_attributes, :allow_destroy => true, reject_if: proc { |attributes| attributes['description'].blank? }

  default_scope -> {order('ends_at ASC, open_at ASC, created_at ASC')}

  has_many :answers, through: :feedback_preferences
  # validates :ends_at, presence: true
  # validates :open_at, presence: true
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: [:show, :edit, :update, :destroy, :rate, :create_rating, :report_blank]
  before_action :set_answer, only: :review_answer
  # before_filter :authenticate_user_is_admin!, only: :review_answer
  before_filter :authenticate_user!
  # GET /reviews
  # GET /reviews.json
  def index
    @answer = Answer.find(params[:answer_id])

    if @answer.assignment.course.students.exists?(current_user.id).nil?
      redirect_to assignment_path(@answer.assignment), alert: "Reviews in this class are only open to enrolled students, so first create a draft of your own submission (you don't need to submit.)" and return
    end


    @trigger = TriggerAction.pending_action("review_required", current_user, @answer.assignment)

    if @trigger.nil? and @answer.reviews_first_seen_at.nil?
      @answer.reviews_first_seen_at = Time.now
      @answer.save!
    end
  end

  # GET /reviews/1
  # GET /reviews/1.json
  def show
    @feedback_items_by_rubric_item = @review.feedback_items.group_by(&:rubric_item_id)
    unless @review.comments.blank?
      (@feedback_items_by_rubric_item["comments"] ||= []) << @review.comments
    end
  end

  # GET /reviews/new
  def new
    @answer = Answer.find(params[:answer_id])
    @review = create_review_for_answer(@answer)
    # raise @review.feedback_items.count.inspect
  end

  # GET /reviews/1/edit
  def edit
    unless @review.user == current_user or current_user.instructor_for?(@review.assignment.course)
      redirect_to @review.assignment, alert: "You can only edit reviews you wrote."
    end

    @answer = @review.answer

    @latest_reviewer_answer = Answer.where(assignment: @answer.assignment, user: current_user).order('updated_at desc').first
  end

  # POST /reviews
  # POST /reviews.json
  def create
    @review = Review.new(review_params.merge(user: current_user, answer: Answer.find(params[:answer_id])))
    @review.assignment = @review.answer.assignment
    @answer = @review.answer
    @answer.increment!(:total_evaluations)
    respond_to do |format|
      if @review.save
        format.html { redirect_to @review, notice: 'Review was successfully created.' }
        format.json { render action: 'show', status: :created, location: @review }
      else
        format.html { render action: 'new' }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reviews/1
  # PATCH/PUT /reviews/1.json
  def update
    unless @review.user == current_user or current_user.instructor_for?(@review.assignment.course)
      redirect_to @review.assignment, alert: "You can only edit reviews you wrote."
    end

    # raise params.inspect
    respond_to do |format|
      @answer= @review.answer
      process_review_triggers_and_answer!(@review)
      if save_review_and_attributes!(@review)
        @review.assignment.delay.regrade_submission(@answer)
        format.html { redirect_to review_first_assignment_path(@review.assignment, recent_review: @review), notice: 'Thanks, we sent that review to your classmate!' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  def report_blank
    # raise params.inspect
    respond_to do |format|
      @answer= @review.answer
      @answer.is_blank_submission = true
      @answer.is_final = false #toallow people to resubmit
      @answer.save!
      process_review_triggers_and_answer!(@review)
      if (@review.update(active: true))
        ReviewMailer.delay.blank_email_notice(@answer, @answer.user_id, @review.assignment_id)
        format.html { redirect_to review_first_assignment_path(@review.assignment, recent_review: @review), notice: 'Thanks, we\'ll stop asking others to review that submission!' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reviews/1
  # DELETE /reviews/1.json
  def destroy
    @assignment = @review.assignment
    @review.destroy
    respond_to do |format|
      format.html { redirect_to @assignment }
      format.json { head :no_content }
    end
  end
  #Create a new review with a particular type
  # such as paired, exchange, final etc
  def create_with_type

    current_user.tried_reviewing = true
    current_user.save!

    @assignment = Assignment.find(params[:id])
    if current_user.experimental_condition(@assignment.course) == "waitlist"
      redirect_to waitlist_assignment_path(params[:id]) and return
    end

    @submitter = User.find_by_email(params[:typed_review][:email])
    review_type = params[:typed_review][:type]
    if @submitter.nil? and review_type != "final"
      redirect_to assignment_path(params[:id]), alert: "We didn't find a user with the address #{params[:typed_review][:email]}" and return
    end
    redirect_to assignment_path(params[:id]), alert: "You can't review yourself!" and return if @submitter==current_user

    @reviewed_already = Review.where(user: current_user, active: true)
    @reviewed_answers = @reviewed_already.map {|r| r.answer_id}
      # raise @reviewed_answers.inspect
    @reviewed_answers << 0 if @reviewed_answers.blank?
    case review_type
    when "exchange"
      @answers = Answer.tagged_with(params[:typed_review][:revision]).where(active: true, submitted:true, user_id: @submitter.id, assignment_id: params[:id])
    when "paired"
      @answers = Answer.tagged_with(params[:typed_review][:revision]).where(active: true,  submitted:true, assignment_id: params[:id]).where("user_id NOT in (?) and answers.id NOT in (?)", [@submitter.id, current_user.id], @reviewed_answers)
    when "final"
      @answers = Answer.where(active: true, submitted:true, review_completed:false, assignment_id: params[:id], is_blank_submission: false).where("user_id NOT in (?) and answers.id NOT in (?)", current_user.id, @reviewed_answers)
    else
      redirect_to assignment_path(params[:id]), alert: "That review type has not opened yet." and return
    end

    if @answers.empty?
      redirect_to assignment_path(params[:id]), alert: "We didn't find any drafts to review" and return
    end

    @answer = @answers.order("(pending_reviews + total_evaluations) ASC, submitted_at desc").first
    @review = create_review_for_answer(@answer, params[:typed_review][:type])

    if review_type == "paired"
      @review.copilot_email = @submitter.email
    end
    @review.save!
    redirect_to edit_review_path(@review)
  end

  def rate
    @trigger = TriggerAction.pending_action("review_required", current_user, @review.assignment)
    if @review.review_method == "normal"
      @feedback_items_by_rubric_item = @review.feedback_items.group_by(&:rubric_item_id)
    else
      @feedback_items_by_rubric_item = {}
    end
    unless @review.comments.blank?
      (@feedback_items_by_rubric_item["comments"] ||= []) << @review.comments
    end

    render layout: "one_column"
  end

  def create_rating
    respond_to do |format|
      if @review.update(review_params.merge(rating_completed: true))
        @my_answers = Answer.where({active: true, assignment_id: @review.answer.assignment_id, user: current_user})
        @next_review = Review.where({active: true, rating_completed: false, answer_id: @my_answers}).first
        if @next_review.blank?
          format.html { redirect_to assignment_path(@review.answer.assignment_id), notice: "Thank you for rating all your reviews" }
          format.json { head :no_content }
        else
          format.html {redirect_to rate_review_path(@next_review), notice: "Thank you for your rating!"}
          format.json { head :no_content }
        end
      else
        format.html { redirect_to action: 'rate', alert: "We couldn't save the rating. Please report a bug" }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  def review_answer
    authenticate_user_is_instructor!(@answer.assignment.course)
    @review = create_review_for_answer(@answer, "final", false)
    if @review.save
      redirect_to edit_review_path @review
    else
      redirect_to @answer.assignment, alert: @review.errors.full_messages.join(",")
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_review
      @review = Review.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def review_params
      params.permit(:answer_id)
      params.permit(:assignment_id)
      params.permit(:typed_review).permit(:email,:type, :revision)

      params.require(:review).permit(:answer_id, :comments, :out_of_box_answer,
        :accurate_rating,
        :concrete_rating,
        :recognize_rating,
        :other_rating_comments,
        :reflection,
        :completion_metadata,
        :copilot_email,
        :review_method,
        :answer_attribute_weights => [:weight],
        :feedback_items_attributes=>[:id, :rubric_item_id, :like_feedback, :wish_feedback, :miscommunication, :score, :review_id,
          :answer_attribute_ids=>[]])
    end

    def set_answer
      @answer = Answer.find(params[:answer_id])
    end
    def create_review_for_answer(answer, type=nil, force_pending = true)
      reviews = Review.where(answer: answer, user: current_user, assignment: answer.assignment, review_type: type, active:true)
      # if !reviews.empty? and type != "final"
      #   return reviews.first
      # end
      #else
      if force_pending
        pending_reviews = Review.where(user: current_user, active: false)
        pending_reviews.each do |r|
          if(r.answer.assignment_id == answer.assignment_id and r.review_type==type)
            #return the first pending review from this student

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/reviews/_answer_for_rating.html.erb
<div class="assignment_instructions">
    <h1><%= link_to answer.assignment.title, answer.assignment %>
    </h1>
</div>

<div class="row-fluid">
  <div class="assignment-rubric">
    <div class="assignment-rubric-content"%>
        <%= yield %>
    </div>

    <%= form_for(@review, url: create_rate_review_path(@review), method: :post) do |f| %>
    <p>Please answer honestly. Your feedback will be kept anonymous. How do you rate the following statements?</p>
    <div class="form-group">
      <%= f.label :accurate_rating, "\"The reviewer accurately assessed my work on this assignment\"" %>
       <%= f.select :accurate_rating, options_for_select([["strongly disagree","1"], ["disagree", "2"], ["somewhat disagree","3"], ["somewhat agree","4"], ["agree","5"],
       ["strongly agree", "6"]], @review.accurate_rating), prompt: "Choose one" %>
    </div>
    <div class="form-group">
      <%= f.label :concrete_rating, "\"The reviewer provided concrete, actionable steps I can take to improve my  work in this class\""%>
       <%= f.select :concrete_rating, options_for_select([["strongly disagree","1"], ["disagree", "2"], ["somewhat disagree","3"], ["somewhat agree","4"], ["agree","5"],
       ["strongly agree", "6"]], @review.concrete_rating), prompt: "Choose one" %>
    </div> 
    <div class="form-group">
      <%= f.label :recognize_rating, "\"The reviewer helped me to recognize a problem with my work that I had not  before recognized\"" %>
      <%= f.select :recognize_rating, options_for_select([["strongly disagree","1"], ["disagree", "2"], ["somewhat disagree","3"], ["somewhat agree","4"], ["agree","5"],
       ["strongly agree", "6"]], @review.recognize_rating), prompt: "Choose one" %>
    </div>
    <div class="form-group">
      <%=f.label :other_rating_comments, "Other comments?" %>
      <%= f.text_area :other_rating_comments, class:"form-control" %>
    </div>
    <div class="form-group">
      <%= f.submit "Submit and rate next review", class: "btn btn-primary" %>
    </div>
    <%end %>
  </div>
  <h3>Your submission</h3>
  <div class="field span8">
    <div class="edited-content">
      <%= sanitize Format.markdown answer.response unless answer.response.nil? %>
    </div>
  </div>
</div>

app/views/reviews/_answers.html.erb
<%= content_for :title do %>
Reviewing <%= answer.assignment.title %>
<% end %>

<span id="reviewingPage" <%= raw('data-force-tour="true"') if current_user.sign_in_count == 1 %>></span>
<%= yield %>
<% content_for :local_nav do %>
    <li><%= link_to answer.assignment.title, answer.assignment %></li>
<% end %>

<div class="row-fluid syncHighlighting">

<% if !answer.assignment.example.blank?%>
  
  <div class="col-md-6">
    <div class="paper">
    	<h3 id="student-work">Give feedback on this submission</h3>
      <%= sanitize answer.response unless answer.response.nil? %>
    </div>
  </div>
  <div class="paper col-md-6">
  <% if (@answer.assignment.id != 39 && @answer.assignment.id != 44) %>
  	<h3 id="excellent-work">Here's an example of excellent work
  	<small>Compare work to this example to suggest improvements</small></h3>
  <% end %>
    <div style="opacity: 0.6;"><%= sanitize answer.assignment.example %></div>
  </div>
<% else %>
  <div class="paper">
    <h3 id="student-work">Give feedback on this submission</h3>
    <%= sanitize answer.response unless answer.response.nil? %>
  </div>
<% end %>
</div>

app/views/reviews/_answers_wide.html.erb
<div class="assignment_instructions">
    <h1><%= link_to answer.assignment.title, answer.assignment %>
    </h1>
    <div class="assignment-description">
      <%= sanitize answer.assignment.description %>
    </div>
</div>

<div class="row">
  <div class="assignment-rubric">
    <div class="assignment-rubric-content"%>
        <%= yield %>
    </div>
  </div>

  <div class="field">
    <div class="edited-content">
      <%= sanitize Format.markdown answer.response unless answer.response.nil? %>

      <%= render partial:"answers/attachments", locals: {answer: answer} %>
    </div>
  </div>
</div>

app/views/reviews/_answers_with_reviews.html.erb
<table class="table">
  <thead>
    <tr>
      <th>Revision Name</th>
      <th>Preview</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% answers.each do |answer| %>
    <tr>
      <td><%= answer.revision_name.blank? ? "<em>Unnamed</em>".html_safe : answer.revision_name %></td>
      <td><%= sanitize truncate(answer.response, length:50, escape: false) or "<em>Not found</em>" %></td>
      <td><%= link_to "Read with reviews", answer_reviews_path(answer) %></td>
    </tr>
    <% end %> 
  </tbody>
</table>

app/views/reviews/_browser.html.erb
  <div class="assignment-rubric span4">
    Show reviews for <div class="btn-group">
      <button type="button" class="btn dropdown-toggle active-revision" data-toggle="dropdown">
        <%= answer.revision_name %> <span class="caret"></span>
      </button>
      <ul class="dropdown-menu" role="menu">
        <% answer.versions.each do |v| %>
        <li><%= link_to v.revision_name, answer_reviews_path(v), remote: true %></li>
        <% end %>
      </ul>
      </div>
  	<div class="assignment-rubric-content"%>
        <%= yield %>
    </div>
  </div>

app/views/reviews/_feedback.html.erb
<style type="text/css">
  .rubric {margin: 0;}
  .rubric li {list-style-type: none; background-color:#efefef; margin:20px 0; padding:10px; -webkit-border-radius:4px; -moz-border-radius:4px; border-radius:4px;}
  </style>
  <% if trigger.nil? or current_user.instructor_for?(@answer.assignment.course) %>
    <ul class="rubric">
      <% unless feedback_items_by_rubric_item["comments"].nil? %>

      <% if (@answer.assignment.id != 39 && @answer.assignment.id != 44) || ((@answer.assignment.id == 39 || @answer.assignment.id == 44) && !@answer.previous_version.nil?) %>
        <li>
          <strong>Overall feedback:</strong>
          <br/>
          <legend></legend>
          <% feedback_items_by_rubric_item["comments"].each.with_index(1) do |comment,i| %>
            <% next if comment.nil? %>
              <div class="row">
                <div class="col-sm-2 col-md-3">
                  <div class="glyphicon glyphicon-user reviewer<%= i %>"> <%= "(Staff)" if feedback_items_by_rubric_item["reviewers"][i-1].instructor_for?(@answer.assignment.course) %>
                  </div>
                </div>
                <div class="col-sm-10 col-md-9">
                  <p><%=Format.markdown comment %></p>
                </div>
              </div>
          <% end %>
        </li>
      <% end %>
      <% end %>
      <% answer.assignment.rubric_items.each do |r| %>
        <li>
          <strong><%= r.short_title %></strong>
          <!-- <span class="pull-right label">Max: <%=r.max %><%= "(#{r.max_label})" unless r.max_label.blank?%></span> -->
          <br/>
          <legend></legend>
          <%= sanitize r.title %>
          <% if feedback_items_by_rubric_item[r.id].nil? %>
          No review.
          <% else %>
            <div class="row-fluid">
                <% answer.assignment.rubric_items.find(r.id).answer_attributes.each do |a_attr| %>
                  <div class="row">
                    <div class="col-sm-12">
                      <p><%= a_attr.description %></p>
                        <% if a_attr.attribute_type != "binary" %>
                          <% feedback_items_by_rubric_item[r.id].each.with_index(1) do |f,i| %>
                            <div class="glyphicon glyphicon-user reviewer<%= i%10 %> reviewer-success" style="display: block;">
                              <% next if f.feedback_item_attributes.where(answer_attribute: a_attr).first.nil? %>
                              <% weight= f.feedback_item_attributes.where(answer_attribute: a_attr).first.weight %>
                              <%= "(Staff)" if f.review.user.instructor_for?(@answer.assignment.course) %>
                                <span class="display-attribute-weight" data-options="<%= a_attr.attribute_type%>" data-score="<%= weight %>"><%= weight %></span>
                                <div class="progress" style="height: 5px">
                                  <div class="progress-bar" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: <%= weight*100 %>%; height: 20px;">
                                  </div>
                                </div>
                            </div>
                          <% end %>
                        <% else %>
                        <% yes_count = a_attr.feedback_items.where(review_id: @answer.reviews.pluck(:id)).count 
                           review_count = @answer.reviews.where(active: true).count 
                        %>
                          Yes: <%= yes_count %> <div class="glyphicon glyphicon-user reviewer1 reviewer-success"></div>
                         
                          &nbsp;
                          No: <%= review_count - yes_count %>  <div class="glyphicon glyphicon-user reviewer3 reviewer-failure"></div>
                        <% end %>
                    </div>
                  </div>
                  <legend></legend>
                <% end %>
              <% feedback_items_by_rubric_item[r.id].each.with_index(1) do |f,i| %>

                  <% unless f.like_feedback.blank? %>
                  <div class="row">
                    <div class="col-sm-2 col-md-3">
                      <div class="glyphicon glyphicon-user reviewer<%= i%10 %>"></div>
                    </div>
                    <div class="col-sm-10 col-md-9">
                      <p><%= f.like_feedback %></p>
                    </div>
                  </div>
                  <% end %>

              <% end %>
            </div>
          <% end %>
        </li>
      <% end %>
    </ul>
  <% else %>
    <div class="well">
      <h2>Reviews locked!</h2>
      <p>
        To see your reviews, you need review others first. You have <strong><%= trigger.count %> reviews</strong> to complete before you can see your own review.
      </p>

        <%= link_to "Give feedback now", create_typed_review_assignment_path(answer.assignment_id,assignment_id:answer.assignment_id,typed_review:{type:"final", revision:"Final Draft"}), method: :post, class: "btn btn-primary" %>

    </div>
  <% end %>

app/views/reviews/_list.html.erb
<p>Here's how your peers assessed you.</p>
<style type="text/css">
.rubric {margin: 0;}
.rubric li {list-style-type: none; background-color:#efefef; margin:20px 0; padding:10px; -webkit-border-radius:4px; -moz-border-radius:4px; border-radius:4px;}
</style>
<ul class="rubric">
  <% answer.assignment.rubric_items.each do |r| %>
    <li>
      <strong><%= r.short_title %></strong>
      <!-- <span class="pull-right label">Max: <%=r.max %><%= "(#{r.max_label})" unless r.max_label.blank?%></span> -->
      <br/>
      <legend></legend>
      <%= sanitize r.title %>
      <% if feedback_items_by_rubric_item[r.id].nil? %>
      No review.
      <% else %>
        <% feedback_items_by_rubric_item[r.id].each.with_index(1) do |f,i| %>
          <table>
          <% answer.assignment.rubric_items.find(r.id).answer_attributes.each do |a_attr| %>
            <tr>
              <% if f.answer_attributes.include?(a_attr) %>
                <td>
                  <button class="btn btn-xs btn-default btn-checkbox-yes btn-success" disabled:"disabled">Yes</button> &nbsp;<%= "(Staff)" if f.review.user.instructor_for?(answer.assignment.course) %>
                </td>
                <td style="vertical-align:top;"><%= a_attr.description %></td>
              <% else %>
                <td>
                  <button class="btn btn-xs btn-default btn-checkbox-yes btn-danger" disabled:"disabled">No</button> &nbsp;<%= "(Staff)" if f.review.user.instructor_for?(answer.assignment.course) %>
                </td>
                <td style="vertical-align:top;"><%= a_attr.description %></td>
              <% end %>
            </tr>
          <% end %>
          </table>
          <% unless f.like_feedback.blank? %>
            <p><strong>Comments:</strong> <%= f.like_feedback %></p>
            <!-- <p><strong>Wish: </strong><%= f.wish_feedback %></p> -->
          <% end %>
        <% end %>
      <% end -%>
    </li>
  <% end %>
  <% unless feedback_items_by_rubric_item["comments"].nil? %>
  <li>
    <strong>Overall feedback:</strong>
    <% feedback_items_by_rubric_item["comments"].each.with_index(1) do |comment,i| %>
      <% next if comment.nil? %>
      <p><strong>Comment</strong> <%= Format.markdown comment %> </p>
    <% end %>
  </li>
  <% end %>
</ul>

app/views/reviews/_list_multiple.html.erb
<% content_for :context_menu do %>
  <%= render partial: "reviews/feedback", locals: {feedback_items_by_rubric_item: feedback_items_by_rubric_item, answer: answer, trigger: @trigger} %>
  <br/>
  <div class="row-fluid">
    <% if answer.reviews.where(active: true, rating_completed: false).count > 0 %>
      <div class="col-sm-8 control-label">Help us provide reviewers better reviewing hints.</div>
      <div class="col-sm-4"><%= link_to "Rate reviews", rate_review_path(answer.reviews.where(active: true, rating_completed: false).first), class: "btn btn-default" %></div></div>
    <% end %>
  <% if show_revision_link %>
      <div class="row-fluid">
        <div class="col-sm-8 control-label">Your grade will be based on your revised (and improved) work.</div>
        <div class="col-sm-4"><%= link_to "Revise submission", reflect_answer_path(answer), class: "btn btn-primary"%></div>
      </div>
      <% if !answer.review_completed? and !answer.is_final? %>
        <div class="row-fluid">
          <div class="col-sm-8 control-label">If you already have enough feedback, why not save your classmates some time?</div>
          <div class="col-sm-4"><%= link_to "Stop reviewing", unsubmit_for_feedback_answer_path(answer), :class=>"btn btn-danger", :role=>"button", :method=>:post %></div>
        </div>
      <% end %>
      <% if answer.review_completed? %>
        <div class="row-fluid">
          <div class="col-sm-12">
            <p><strong>No longer being reviewed.</strong></p>
          </div>
        </div>
      <% end %>
  <% end %>
  <% if current_user.instructor_for?(answer.assignment.course) %>
  <div class="row-fluid">
    <div class="col-sm-12"><%= link_to "Review as staff", review_answer_path(answer), method: :post %></div>
  </div>
  <% end %>

<% end %>

app/views/reviews/edit.html.erb
<%= render partial:'form', layout:"answers", :locals=>{answer:@review.answer} %>

app/views/reviews/index.html.erb
<%= render partial: "list_multiple", layout:"answers", :locals=>{answer: @answer,feedback_items_by_rubric_item: @answer.feedback_items_by_rubric_item, show_revision_link: true} %>

app/views/reviews/index.js.erb
$(".assignment-rubric-content").html('<%= escape_javascript render partial: "list_multiple", layout:nil, :locals=>{answer: @answer,feedback_items_by_rubric_item: @feedback_items_by_rubric_item} %>')
$(".active-revision").html('<%=j @answer.revision_name.join(" ") %> <span class="caret"></span>')

app/views/reviews/rate.html.erb
<% if @trigger.nil? %>
	<%= render partial: "list", layout:"answer_for_rating", :locals=>{answer: @review.answer,feedback_items_by_rubric_item: @feedback_items_by_rubric_item} %>
<% else %>
    <div class="well">
      <h2>Reviews locked!</h2>
      <p>
        To see your reviews, you need review others first. You have <strong><%= @trigger.count %> reviews</strong> to complete before you can see your own review.
      </p>
        <%= link_to "Give feedback now", create_typed_review_assignment_path(@review.assignment_id,assignment_id:@review.assignment_id,typed_review:{type:"final", revision:"Final Draft"}), method: :post, class: "btn btn-primary" %>
    </div>
<% end %>

app/views/reviews/show.html.erb
<%= render partial: "list", layout:"answers", :locals=>{answer: @review.answer,feedback_items_by_rubric_item: @feedback_items_by_rubric_item} %>